version: '3.8'

services:
  position-service:
    build:
      context: .
      target: position-service
    ports:
      - "8080:8080"
    restart: always
    environment:
      - PORT=8080

  order-service-producer:
    build:
      context: .
      target: position-service # Using builder artifacts
    entrypoint: ["/app/bin/order_service"]
    command: ["--csv-file=/app/order_updates.csv", "--target-url=http://position-service:8080/events", "--rate-limit-mps=50"]
    depends_on:
      - position-service
    volumes:
      - ./order_updates (1).csv:/app/order_updates.csv
